### PR TITLE
MAGENTO-2380: added frontend portal to prevent display of coupon code…

### PR DESCRIPTION
**Pull request by aaron-martin**
… when one does not exist

# Pull Request Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

- [X] Bug fix
- [ ] New feature
- [ ] This change requires a documentation update

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I updated the CHANGELOG.md

### CODE REVIEW

**Comment by augsteyer** [comment]
which PWA versions are your running for this? I am getting a few errors with unrecognized routes
e.g. `Module not found: Error: Can't resolve './AuthRoutes' in '/Users/konstantin/Development/shopgate/environments/connect/themes/theme-gmd/node_modules/@shopgate/pwa-common/collections`
I am also not seeing a alpha/beta/rc tag for this fix.

**Comment by sznowicki** [comment]
@augsteyer PWA5

**Comment by augsteyer** [comment]
Looks good on pwa5, will this change be fine on pwa 6.1?

**Review by augsteyer — APPROVED** [review]

**Comment by andre-kraus** [comment]
Sorry for sneaking into this PR, but could you also add the new frontend folder to the .travis.yml and trigger at least an npm audit in there.

**Review by andre-kraus — CHANGES_REQUESTED** [review]
Sorry for sneaking into this PR, but could you also add the new frontend folder to the .travis.yml and trigger at least an npm audit in there.

**Comment by aaron-martin** [comment]
@andre-kraus 
I updated the travis yml file.

**Review by andre-kraus — APPROVED** [review]

**Pull request merged**
